/* Generated By:JavaCC: Do not edit this line. ProgramParserConstants.java */
package at.ac.tuwien.kr.dlprogram.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProgramParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAF = 6;
  /** RegularExpression Id. */
  int IDENTIFIER = 7;
  /** RegularExpression Id. */
  int CONJUNCTION = 8;
  /** RegularExpression Id. */
  int IMPLY = 9;
  /** RegularExpression Id. */
  int ENDOFSTATEMENT = 10;
  /** RegularExpression Id. */
  int COMPARISON = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DOUBLE = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int VARIABLE = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int TIMES = 18;
  /** RegularExpression Id. */
  int DIVIDE = 19;
  /** RegularExpression Id. */
  int LEFTBRACKET = 20;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"not\"",
    "<IDENTIFIER>",
    "\",\"",
    "\":-\"",
    "\".\"",
    "<COMPARISON>",
    "<INTEGER>",
    "<DOUBLE>",
    "<STRING>",
    "<VARIABLE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
