/* Generated By:JavaCC: Do not edit this line. ProgramParserConstants.java */
package at.ac.tuwien.kr.dlprogram.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProgramParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAF = 6;
  /** RegularExpression Id. */
  int CONJUNCTION = 7;
  /** RegularExpression Id. */
  int IMPLY = 8;
  /** RegularExpression Id. */
  int ENDOFSTATEMENT = 9;
  /** RegularExpression Id. */
  int COMPARISON = 10;
  /** RegularExpression Id. */
  int DL_ATOM = 11;
  /** RegularExpression Id. */
  int LEFT_SQUARE_BRACKET = 12;
  /** RegularExpression Id. */
  int RIGHT_SQUARE_BRACKET = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int VARIABLE = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int TIMES = 21;
  /** RegularExpression Id. */
  int DIVIDE = 22;
  /** RegularExpression Id. */
  int LEFTBRACKET = 23;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 24;
  /** RegularExpression Id. */
  int UPLUS = 25;
  /** RegularExpression Id. */
  int UMINUS = 26;
  /** RegularExpression Id. */
  int DLPREDICATE = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"not\"",
    "\",\"",
    "\":-\"",
    "\".\"",
    "<COMPARISON>",
    "\"DL\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<DOUBLE>",
    "<STRING>",
    "<VARIABLE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"+=\"",
    "\"-=\"",
    "<DLPREDICATE>",
    "\";\"",
  };

}
